# Generated by Django 4.1.5 on 2023-01-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('metascore', models.PositiveIntegerField(verbose_name='Metascore')),
                ('img_src', models.CharField(max_length=250, verbose_name='Img_src')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('entity_name', models.CharField(default='', max_length=250, verbose_name='Entity_name')),
                ('score', models.PositiveIntegerField(verbose_name='Score')),
                ('publication', models.CharField(max_length=250, verbose_name='Publication')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('review_text', models.TextField(default=' ', verbose_name='Review_text')),
                ('entity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reviews.entity')),
            ],
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('entity_name', 'publication', 'review_text'), name='unique'),
        ),
    ]
