# Generated by Django 4.1.5 on 2023-01-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userscore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userscore', models.PositiveIntegerField(verbose_name='Userscore')),
                ('entity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reviews.entity')),
            ],
        ),
    ]
