# Generated by Django 4.1.5 on 2023-01-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique',
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default=' ', verbose_name='Review_text'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('name', 'publication', 'review_text'), name='unique'),
        ),
    ]
