# Generated by Django 4.1.5 on 2023-01-08 03:29

from django.db import migrations

def create_data(apps,schema_editor):
    Review = apps.get_model('reviews','Student')
    Review(name="Name",score=0,publication="Example").save()
class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_data)
    ]
